apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cloudshopproductapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudshopproductapi-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cloudshopclient-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudshopclient-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
