apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshopproductapi-deployment
spec:
  selector:
    matchLabels:
      app: cloudshopproductapi
  template:
    metadata:
      labels:
        app: cloudshopproductapi
    spec:
      containers:
        - name: cloudshopproductapi
          image: cloudshopacr.azurecr.io/cloudshopproductapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              value: mongodb://mongo-service:27017
              # valueFrom:
              #   configMapKeyRef:
              #     name: mongo-configmap
              #     key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets: 
        - name: acr-secret
---

apiVersion: v1
kind: Service
metadata:
  name: cloudshopproductapi-service
spec:
  selector:
    app: cloudshopproductapi
  ports:
  - protocol: TCP
    port: 80

