apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshopclient-deployment
  labels:
    app: cloudshopclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudshopclient
  template:
    metadata:
      labels:
        app: cloudshopclient
    spec:
      containers:
        - name: cloudshopclient
          image: cloudshopacr.azurecr.io/cloudshopclient
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ProductAPIUrl
              valueFrom:
                configMapKeyRef:
                  name: cloudshopproductapi-configmap
                  key: cloudshopproductapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets: 
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cloudshopclient-service
spec:
  type: LoadBalancer
  selector:
    app: cloudshopclient
  ports:
    - protocol: TCP
      port: 80