apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudshopproductapi-deployment
spec:
  selector:
    matchLabels:
      app: cloudshopproductapi
  template:
    metadata:
      labels:
        app: cloudshopproductapi
    spec:
      containers:
      - name: cloudshopproductapi
        image: greem364/cloudshopproductapi
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: DatabaseSettings__ConnectionString
            value: mongodb://mongo-service:27017
            # valueFrom:
            #   configMapKeyRef:
            #     name: mongo-configmap
            #     key: connection_string
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "0.2" 
---

apiVersion: v1
kind: Service
metadata:
  name: cloudshopproductapi-service
spec:
  type: NodePort  
  selector:
    app: cloudshopproductapi
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 31000

